Add object conversion docs
canjs/can-observable-bindings pull request #16
Opened 2019-10-18 19:58 UTC by cherifGsoul

Docs for object conversion feature.

2019-10-18 20:28 UTC, phillipskevin requested changes

2019-10-18 20:28 UTC, phillipskevin commented on doc/from-attribute.md
> +It is possible to pass a conversion object for attributes that need to be paresd before setting the property, the passed object can be `JSON` object or anything implements `parse` and `stringify` met
`paresd` -> `parsed`

2019-10-18 20:28 UTC, phillipskevin commented on doc/from-attribute.md
> +It is possible to pass a conversion object for attributes that need to be paresd before setting the property, the passed object can be `JSON` object or anything implements `parse` and `stringify` met
Also, I would say 

> the passed object can be any object that has `parse` and `stringify` functions, such as the global [JSON object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON).

2019-10-18 21:23 UTC, cherifGsoul commented on doc/from-attribute.md
> +It is possible to pass a conversion object for attributes that need to be paresd before setting the property, the passed object can be `JSON` object or anything implements `parse` and `stringify` met
Updated

2019-11-04 15:28 UTC, phillipskevin approved these changes

2019-11-04 16:02 UTC, merged